sybinit.release_directory: USE_DEFAULT
sqlsrv.server_name: ${SERVER_NAME}
sqlsrv.sa_login: sa
sqlsrv.sa_password: ${SA_PASSWD}
sqlsrv.default_language: us_english
sqlsrv.language_install_list: USE_DEFAULT
sqlsrv.language_remove_list: USE_DEFAULT
sqlsrv.default_characterset: utf8
sqlsrv.characterset_install_list: USE_DEFAULT
sqlsrv.characterset_remove_list: USE_DEFAULT
sqlsrv.sort_order: binary
