sybinit.release_directory: USE_DEFAULT
sybinit.product: sqlsrv
sqlsrv.server_name: $SERVER_NAME
sqlsrv.sa_password: $SA_PASSWD
sqlsrv.new_config: yes
sqlsrv.do_add_server: yes
sqlsrv.network_protocol_list: tcp
sqlsrv.network_hostname_list: $LISTEN_IP
sqlsrv.network_port_list: $LISTEN_PORT
sqlsrv.application_type: USE_DEFAULT
sqlsrv.server_page_size: $PAGE_SIZE
sqlsrv.force_buildmaster: no
sqlsrv.master_device_physical_name: $INSTALL_DIR/data/master.dat
sqlsrv.master_device_size: 1024
sqlsrv.master_database_size: 516
sqlsrv.errorlog: USE_DEFAULT
sqlsrv.do_upgrade: no
sqlsrv.sybsystemprocs_device_physical_name: $INSTALL_DIR/data/sysprocs.dat
sqlsrv.sybsystemprocs_device_size: 1024
sqlsrv.sybsystemprocs_database_size: 516
sqlsrv.sybsystemdb_device_physical_name: $INSTALL_DIR/data/sybsysdb.dat
sqlsrv.sybsystemdb_device_size: 512
sqlsrv.sybsystemdb_database_size: 256
sqlsrv.tempdb_device_physical_name: $INSTALL_DIR/data/tempdbdev.dat
sqlsrv.tempdb_device_size: 1024
sqlsrv.tempdb_database_size: 516
sqlsrv.default_backup_server: ${SERVER_NAME}_back
#sqlsrv.addl_cmdline_parameters: PUT_ANY_ADDITIONAL_COMMAND_LINE_PARAMETERS_HERE
sqlsrv.do_configure_pci: no
sqlsrv.sybpcidb_device_physical_name: PUT_THE_PATH_OF_YOUR_SYBPCIDB_DATA_DEVICE_HERE
sqlsrv.sybpcidb_device_size: USE_DEFAULT
sqlsrv.sybpcidb_database_size: USE_DEFAULT
# If sqlsrv.do_optimize_config is set to yes, both sqlsrv.avail_physical_memory and sqlsrv.avail_cpu_num need to be set.
sqlsrv.do_optimize_config: no
sqlsrv.avail_physical_memory: PUT_THE_AVAILABLE_PHYSICAL_MEMORY_FOR_ASE_IN_OPTIMIZATION
sqlsrv.avail_cpu_num: PUT_THE_AVAILABLE_NUMBER_CPU_FOR_ASE_IN_OPTIMIZATION